version: "3.9"

services:
  api:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: pastelaria-api:latest
    container_name: pastelaria-api
    hostname: api
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    command: bash -c "/usr/local/bin/docker-entrypoint.sh && php-fpm"
    networks:
      pastelaria-network:
          ipv4_address: 172.30.0.100
    depends_on:
      - mysql
      - redis
      - elasticsearch
    healthcheck:
      test: bash -c "[ -f /var/www/.composer_installed ] && [ -f /var/www/.migrations_executed ] &&  [ -f /var/www/.env ]"
      interval: 1m
      timeout: 5s
      retries: 30

  mysql:
    image: mysql:5.7
    container_name: pastelaria-db
    hostname: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --init-file /tmp/init.sql
    ports:
      - 3389:3306
    volumes:
      - ./docker/mysql/init.sql:/tmp/init.sql
      - ./docker/mysql/db:/var/lib/mysql
    networks:
      pastelaria-network:
          ipv4_address: 172.30.0.101

  nginx:
    image: nginx:1.23.1-alpine
    container_name: pastelaria-nginx
    hostname: nginx
    ports:
      - 8099:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      pastelaria-network:
          ipv4_address: 172.30.0.102
    depends_on:
      api:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: pastelaria-elasticsearch
    hostname: elasticsearch
    environment:
      - node.name=pastelaria-elasticsearch
      - discovery.type=single-node
      - discovery.seed_hosts=pastelaria-elasticsearch
      #- cluster.initial_master_nodes=pastelaria-elasticsearch
      - cluster.name=pastelaria-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
      - "9301:9300"
    networks:
      pastelaria-network:
        ipv4_address: 172.30.0.103
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis:
    image: redis:alpine3.18
    container_name: redis
    hostname: redis
    networks:
      pastelaria-network:
        ipv4_address: 172.30.0.104

networks:
  pastelaria-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1